### ISSUE TITLE
Expand a bit on what the different reports are actually measuring

### ISSUE THREAD

**Issue by rconde01** [MetanoKid/cpp-build-analyzer#44]
Maybe I'm just being daft, but I would appreciate a sentence or two on what each of the reports are measuring. I can guess but i'm not totally sure.

**Comment by MetanoKid** [comment]
Sure, it would be very useful having some section with directions on how to interpret each report.

Thanks for the suggestion!

**Comment by MetanoKid** [comment]
I've added a Wiki to the repo and added some sections outlining the contents of each report.
Hope they shed some extra light!

https://github.com/MetanoKid/cpp-build-analyzer/wiki

Thanks for sharing whether they helped 🙂

**Comment by rconde01** [comment]
Thanks for these updates - they definitely helped. I need to think about whether i have any further questions.
